### ISSUE TITLE
[Bug] Unity mode: Unable to select unity race, No click go when inheritance event appear

### ISSUE THREAD

**Issue by boshido** [Magody/Umaplay#76]
Version: 0.4.0
after merge request #73 applied

My Environment Setup
- ADB by using usb
- SCRCPY - Google Pixel 2 XL 
   scrcpy --max-fps 10 -b 2M --video-codec=h264 --no-audio
- Sepearate YOLO/OCR api run in Linux (Python 3.10, CUDA 13.0 update 2)
   uvicorn server.main_inference:app --reload --host 0.0.0.0 --port 8001
- Windows 11 VM (Python 3.12)

My configuration
```json
{
  "id": "f751718f-b0e9-4d8a-9bde-3f568b7468de",
  "name": "Maruzensky Swim",
  "group": null,
  "priorityStats": [
    "SPD",
    "STA",
    "WIT",
    "PWR",
    "GUTS"
  ],
  "targetStats": {
    "SPD": 1150,
    "STA": 600,
    "PWR": 800,
    "GUTS": 600,
    "WIT": 1000
  },
  "minimalMood": "GOOD",
  "juniorStyle": "front",
  "skillsToBuy": [
    "Mile Corners ○",
    "Right-Handed ○",
    "Ignited Spirit SPD",
    "Hanshin Racecourse ○"
  ],
  "skillPtsCheck": 600,
  "plannedRaces": {},
  "plannedRacesTentative": {},
  "raceIfNoGoodValue": true,
  "prioritizeHint": false,
  "weakTurnSv": 1.75,
  "racePrecheckSv": 3.5,
  "lobbyPrecheckEnable": false,
  "juniorMinimalMood": null,
  "goalRaceForceTurns": 5,
  "unityCupAdvanced": {
    "burstAllowedStats": [
      "STA",
      "GUTS"
    ],
    "scores": {
      "rainbowCombo": 0.5,
      "whiteSpiritFill": 0.4,
      "whiteSpiritExploded": 0.13,
      "whiteComboPerFill": 0.25,
      "blueSpiritEach": 0.5,
      "blueComboPerExtraFill": 0.25
    },
    "multipliers": {
      "juniorClassic": {
        "white": 1.5,
        "whiteCombo": 1.5,
        "blueCombo": 1.5
      },
      "senior": {
        "white": 1,
        "whiteCombo": 1,
        "blueCombo": 1
      }
    },
    "opponentSelection": {
      "race1": 2,
      "race2": 1,
      "race3": 1,
      "race4": 1,
      "defaultUnknown": 1
    }
  },
  "event_setup": {
    "supports": [
      {
        "slot": 0,
        "name": "Kitasan Black",
        "rarity": "SSR",
        "attribute": "SPD",
        "priority": {
          "enabled": true,
          "scoreBlueGreen": 0.75,
          "scoreOrangeMax": 0.5,
          "skillsRequiredForPriority": [],
          "recheckAfterHint": false
        },
        "rewardPriority": [
          "skill_pts",
          "stats",
          "hints"
        ],
        "avoidEnergyOverflow": true
      },
      {
        "slot": 1,
        "name": "Silence Suzuka",
        "rarity": "SSR",
        "attribute": "SPD",
        "priority": {
          "enabled": true,
          "scoreBlueGreen": 0.75,
          "scoreOrangeMax": 0.5,
          "skillsRequiredForPriority": [],
          "recheckAfterHint": false
        },
        "rewardPriority": [
          "skill_pts",
          "stats",
          "hints"
        ],
        "avoidEnergyOverflow": true
      },
      {
        "slot": 2,
        "name": "Fuji Kiseki",
        "rarity": "SR",
        "attribute": "WIT",
        "priority": {
          "enabled": true,
          "scoreBlueGreen": 0.75,
          "scoreOrangeMax": 0.5,
          "skillsRequiredForPriority": [
            "Mile Corners ○"
          ],
          "recheckAfterHint": false
        },
        "rewardPriority": [
          "skill_pts",
          "stats",
          "hints"
        ],
        "avoidEnergyOverflow": true
      },
      {
        "slot": 3,
        "name": "Marvelous Sunday",
        "rarity": "SR",
        "attribute": "WIT",
        "priority": {
          "enabled": true,
          "scoreBlueGreen": 0.75,
          "scoreOrangeMax": 0.5,
          "skillsRequiredForPriority": [],
          "recheckAfterHint": false
        },
        "rewardPriority": [
          "skill_pts",
          "stats",
          "hints"
        ],
        "avoidEnergyOverflow": true
      },
      {
        "slot": 4,
        "name": "Daiwa Scarlet",
        "rarity": "SR",
        "attribute": "WIT",
        "priority": {
          "enabled": true,
          "scoreBlueGreen": 0.75,
          "scoreOrangeMax": 0.5,
          "skillsRequiredForPriority": [],
          "recheckAfterHint": false
        },
        "rewardPriority": [
          "skill_pts",
          "stats",
          "hints"
        ],
        "avoidEnergyOverflow": true
      },
      {
        "slot": 5,
        "name": "Haru Urara",
        "rarity": "SSR",
        "attribute": "GUTS",
        "priority": {
          "enabled": true,
          "scoreBlueGreen": 0.75,
          "scoreOrangeMax": 0.5,
          "skillsRequiredForPriority": [],
          "recheckAfterHint": false
        },
        "rewardPriority": [
          "skill_pts",
          "stats",
          "hints"
        ],
        "avoidEnergyOverflow": true
      }
    ],
    "scenario": {
      "name": "Unity Cup",
      "avoidEnergyOverflow": true,
      "rewardPriority": [
        "skill_pts",
        "stats",
        "hints"
      ]
    },
    "trainee": {
      "name": "Maruzensky (Summer)",
      "avoidEnergyOverflow": true,
      "rewardPriority": [
        "skill_pts",
        "stats",
        "hints"
      ]
    },
    "prefs": {
      "overrides": {
        "trainee/Maruzensky (Summer)/None/None/Hot Rod#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Let's Play ♪#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Take the Wheel#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Meeting New People Is Trendy ☆#s1": 1,
        "trainee/Maruzensky (Summer)/None/None/Failed training (Get Well Soon!)#s1": 1,
        "trainee/Maruzensky (Summer)/None/None/At Summer Camp (Year 2)#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Acupuncture (Just an Acupuncturist, No Worries! ☆)#s1": 4,
        "trainee/Maruzensky (Summer)/None/None/Victory! (G1)#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Victory! (G2/G3)#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Victory! (Pre/OP)#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Solid Showing (G1)#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Solid Showing (G2/G3)#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Solid Showing (Pre/OP)#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Defeat (G1)#s1": 2,
        "trainee/Maruzensky (Summer)/None/None/Defeat (Pre/OP)#s1": 2,
        "support/Kitasan Black/SPD/SSR/Ah, Friendship#s1": 2,
        "support/Daiwa Scarlet/WIT/SR/I'm Going to Win Tomorrow!#s1": 2,
        "support/Haru Urara/GUTS/SSR/Urara's ☆ Long Shot Dash!#s1": 1,
        "support/Marvelous Sunday/WIT/SR/How To Be More Marvelous ☆#s1": 2
      },
      "patterns": [],
      "defaults": {
        "support": 1,
        "trainee": 1,
        "scenario": 1
      },
      "rewardPriority": [
        "skill_pts",
        "stats",
        "hints"
      ]
    }
  }
}
```

**Unable to select unity race**
Step of reproduce
- Select Unity
- Use SCRCPY as engine
- Run bot as usual until unity race appear
- Bot stuck and doing nothing

**No click go when inheritance event appear**
Step of reproduce
- Select Unity
- Use SCRCPY as engine
- Run bot as usual until inheritance event to get blessing appear
- Bot stuck and doing nothing and stopped itself

VDO:
https://drive.google.com/file/d/1BvGm2DADud96GYB_g8xasC0fSGnPdp-4/view?usp=sharing

Image:
<img width="2309" height="1283" alt="Image" src="https://github.com/user-attachments/assets/2921cd11-c0fd-4775-9b96-c77b67b9a4c7" />

**Comment by Magody** [comment]
Excelent report, will work on this for 0.4.1

Also, it might be nice to have the data you may have at one of these places: debug/ura | debug/unity_cup or datasets/ura/raw | datasets/unity_cup/raw 

I prefer data inside the ' datasets' folder, or both places

With more data model will work better. I don't have Maruzensky, so my YOLO model is overfitted with my 6 most common umas xd


<img width="1079" height="779" alt="Image" src="https://github.com/user-attachments/assets/a66568f7-4ac2-4e79-b32f-baf25a92b43e" />

I'm also retraining the model. I noticed that for 'button_golden' class I only have 3 instances in validation dataset lol, so I think adding more data should fix the problem. something similar for recreation_row, button_pink and riko kashimoto

<img width="817" height="579" alt="Image" src="https://github.com/user-attachments/assets/9676b09f-93aa-487d-9222-937e1257183b" />

Give me some time to address this, thanks

**Comment by boshido** [comment]
Debug file:
[debug.txt](https://github.com/user-attachments/files/23617513/debug.txt)

It seem empty for datasets/unity_cup/raw, datasets/uma/raw in both client and yolo/ocr server
<img width="1739" height="1011" alt="Image" src="https://github.com/user-attachments/assets/e35c6697-0619-4e74-8615-ce7e629b2687" />

Is there any way to generate it ?
or if you have the way to help you for easier to train model better, i'm willing to help

I've never done model training before if you have some guidance it's better for me to start

**Comment by Magody** [comment]
Check the 'debug\unity_cup' folder, there must be some of data there, 

<img width="1136" height="446" alt="Image" src="https://github.com/user-attachments/assets/8e701a4c-9939-4d46-9278-1271e7ac8361" />

**Comment by Magody** [comment]
In the meantime...
I took some screenshots of your 'go' button and your 'unity cup race day' button, and I added them to model training pipeline. I think now it should be able to recognize those objects from your 'Pixel' screen, and that should reduce also the general overfitting of the model

<img width="1914" height="889" alt="Image" src="https://github.com/user-attachments/assets/2abdaa3f-c177-4a31-895d-3a444eac087e" />

After training the model this is the new model accuracy results:

<img width="998" height="510" alt="Image" src="https://github.com/user-attachments/assets/657664b0-17b0-4886-b4d4-d46b4fc55a43" />

still very low for "lobby_rest_summer" icon, uff without enough data is hard to balance all the accuracies

I pushed changes to dev: https://github.com/Magody/Umaplay/pull/78 

please check if the error was solved 

CC: @boshido 

I'm not pushing to main, because I need to validate that this new model it is not broken in another place

**Comment by boshido** [comment]
> Check the 'debug\unity_cup' folder, there must be some of data there,
> 
> <img alt="Image" width="1136" height="446" src="https://private-user-images.githubusercontent.com/37024575/516571977-8e701a4c-9939-4d46-9278-1271e7ac8361.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2MDg0NjQsIm5iZiI6MTc2MzYwODE2NCwicGF0aCI6Ii8zNzAyNDU3NS81MTY1NzE5NzctOGU3MDFhNGMtOTkzOS00ZDQ2LTkyNzgtMTI3MWU3YWM4MzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIwVDAzMDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNjgzYTU1MjI1ZDlmMTIyMzE0YzViOTNkZWU5NTA4MDI4OTI1YjM1YzhmODhlNWY3NmVhODQ5NTA5YmNlZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pGfwn1bt1rnO__4KllZnibkNf7iLeJMmF4Ztjzh7oE4">

My debug directory only contain debug text files and has no unity_cup directory
<img width="1289" height="805" alt="Image" src="https://github.com/user-attachments/assets/4b48c820-f5bc-4b46-9da2-3cdc697bbd14" /> 


I will test on [feature/0.4.1](https://github.com/Magody/Umaplay/tree/feature/0.4.1)

**Comment by boshido** [comment]
After testing I got new problem, 
The bot loop anwser tazuna's question non stop
https://drive.google.com/file/d/1hp0ikpjCROO-QEvsmKlXrxcGwiUtOb5S/view?usp=sharing

[debug2.txt](https://github.com/user-attachments/files/23666762/debug2.txt)

Edited:
I've tested on 0.4.1 branch, all problems still occur.
So, the new patch does not fix anything yet.

**Comment by Magody** [comment]
> The bot loop anwser tazuna's question non stop


uhm I was not able to replicate this, this usually happened to me when using 'URA' scenario instead of 'Unity' or when using low res Screen

So new model didn't work... and you don't have anything in 'debug' folder. I will need you to recolect some screenshots manually of the screens that bot is not able to recognize

please take some screenshots and put them in a drive so I can download them and label them in label-studio. or you may want to do a script to collect the data

So for steam I was using this code :
```
# capture_left_half.py
import os
import time
from datetime import datetime

from core.controllers.steam import SteamController

OUTPUT_DIR = r"temp/steam"        # <-- pick your folder
WINDOW_TITLE = "Umamusume"            # steam window title
FILENAME_PREFIX = "left_half"         # output name prefix

def capture_left_half():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    ctrl = SteamController(window_title=WINDOW_TITLE, capture_client_only=True)

    # 1) Focus the game window
    # if not ctrl.focus():
    #     raise RuntimeError(f"Window '{WINDOW_TITLE}' not found or could not be focused.")

    time.sleep(0.2)  # tiny settle delay

    # 2) Get client-area box in screen coords
    xywh = ctrl._client_bbox_screen_xywh()  # (left, top, width, height)
    if not xywh:
        # Fallback: trigger a full client screenshot to populate bbox
        _ = ctrl.screenshot()
        xywh = ctrl.capture_bbox()

    left, top, width, height = xywh
    half_region = (left, top, width // 2, height)  # LEFT half

    # 3) Capture just the left half of the client area
    img = ctrl.screenshot(region=half_region)

    # 4) Save
    ts = datetime.now().strftime("screenshot_%Y%m%d_%H%M%S")
    out_path = os.path.join(OUTPUT_DIR, f"{FILENAME_PREFIX}_{ts}.png")
    img.save(out_path)
    print(f"Saved: {out_path}")

if __name__ == "__main__":
    capture_left_half()
```


For SCRCPY I was using the same scrcpy terminal (take_screenshot_uma.bat in the same scrcpy folder):
```
@echo off
:: ——————————————————————————————
:: Configuration
set "OUTPUT_DIR=D:\GitHub\UmAutoplay\temp\android"
:: ——————————————————————————————

:: Get a timestamp via PowerShell: YYYYMMDD_HHmmss
for /f "delims=" %%I in (
  'powershell -NoProfile -Command "Get-Date -Format yyyyMMdd_HHmmss"'
) do set "TIMESTAMP=%%I"

:: Build filename
set "FILENAME=screenshot_%TIMESTAMP%.png"

:: Capture & save
adb exec-out screencap -p > "%OUTPUT_DIR%\%FILENAME%"

echo Screenshot saved as %OUTPUT_DIR%\%FILENAME%

```

**Comment by boshido** [comment]
> > The bot loop anwser tazuna's question non stop
> 
> uhm I was not able to replicate this, this usually happened to me when using 'URA' scenario instead of 'Unity' or when using low res Screen
> 
> So new model didn't work... and you don't have anything in 'debug' folder. I will need you to recolect some screenshots manually of the screens that bot is not able to recognize
> 
> please take some screenshots and put them in a drive so I can download them and label them in label-studio. or you may want to do a script to collect the data
> 
> So for steam I was using this code :
> 
> ```
> # capture_left_half.py
> import os
> import time
> from datetime import datetime
> 
> from core.controllers.steam import SteamController
> 
> OUTPUT_DIR = r"temp/steam"        # <-- pick your folder
> WINDOW_TITLE = "Umamusume"            # steam window title
> FILENAME_PREFIX = "left_half"         # output name prefix
> 
> def capture_left_half():
>     os.makedirs(OUTPUT_DIR, exist_ok=True)
> 
>     ctrl = SteamController(window_title=WINDOW_TITLE, capture_client_only=True)
> 
>     # 1) Focus the game window
>     # if not ctrl.focus():
>     #     raise RuntimeError(f"Window '{WINDOW_TITLE}' not found or could not be focused.")
> 
>     time.sleep(0.2)  # tiny settle delay
> 
>     # 2) Get client-area box in screen coords
>     xywh = ctrl._client_bbox_screen_xywh()  # (left, top, width, height)
>     if not xywh:
>         # Fallback: trigger a full client screenshot to populate bbox
>         _ = ctrl.screenshot()
>         xywh = ctrl.capture_bbox()
> 
>     left, top, width, height = xywh
>     half_region = (left, top, width // 2, height)  # LEFT half
> 
>     # 3) Capture just the left half of the client area
>     img = ctrl.screenshot(region=half_region)
> 
>     # 4) Save
>     ts = datetime.now().strftime("screenshot_%Y%m%d_%H%M%S")
>     out_path = os.path.join(OUTPUT_DIR, f"{FILENAME_PREFIX}_{ts}.png")
>     img.save(out_path)
>     print(f"Saved: {out_path}")
> 
> if __name__ == "__main__":
>     capture_left_half()
> ```
> 
> For SCRCPY I was using the same scrcpy terminal (take_screenshot_uma.bat in the same scrcpy folder):
> 
> ```
> @echo off
> :: ——————————————————————————————
> :: Configuration
> set "OUTPUT_DIR=D:\GitHub\UmAutoplay\temp\android"
> :: ——————————————————————————————
> 
> :: Get a timestamp via PowerShell: YYYYMMDD_HHmmss
> for /f "delims=" %%I in (
>   'powershell -NoProfile -Command "Get-Date -Format yyyyMMdd_HHmmss"'
> ) do set "TIMESTAMP=%%I"
> 
> :: Build filename
> set "FILENAME=screenshot_%TIMESTAMP%.png"
> 
> :: Capture & save
> adb exec-out screencap -p > "%OUTPUT_DIR%\%FILENAME%"
> 
> echo Screenshot saved as %OUTPUT_DIR%\%FILENAME%
> ```

sorry for late reply, I was assigned on tons of work so no time to play any games.
I will try generate data for you in 1-3 days

**Comment by boshido** [comment]
**Dataset**
https://drive.google.com/drive/folders/1zROsVBSpVzcufp1FohKbv0EiGug5YPgI?usp=sharing
